= Managing Hazelcast through the domain.xml

The _domain.xml_ file can be found at `<Payara Installation Directory>/glassfish/domains/<Domain Name>/config/`.

Configuring the persistence provider via the _domain.xml_ file requires
editing the _availability-service_ settings of a cluster configuration.

If the domain has not yet been started, some tags listed here may not exist.

== Enabling Hazelcast

* Open the _domain.xml_ file in a text editor.

* Add `enabled="true"` to the `hazelcast-runtime-configuration` tag:

----
<config name="server-config">
    [...]
    <hazelcast-runtime-configuration enabled="true"></hazelcast-runtime-configuration>
    [...]
</config>
----

== Configuring Hazelcast

* Open the _domain.xml_ file in a text editor.

* Find the _<hazelcast-runtime-configuration>_ tag under the appropriate
_<config>_ tag (e.g. _<config name="server-config">_ for the Admin
Server) and add one or more of the following properties to it as
required:

[cols=",,",options="header",]
|====
|Property |Admin Console Equivalent |Description
|hazelcast-configuration-file |Override Configuration File |Specifies
the Hazelcast configuration file to use. The path specified must be
relative to the domain config directory.

|start-port |Start Port |Determines the port to start Hazelcast on. If
this port it in use, Hazelcast will increment this port until it finds
one it can use.

|multicast-group |Multicast Group |The multicast group for
communications in the Hazelcast cluster.

|multicast-port |Multicast Port |The multicast port for group
communications in the Hazelcast cluster.

|jndi-name |JNDI Name |The JNDI name to bind the Hazelcast instance to.

|host-aware-partitioning |Host Aware Partitioning |Enables/disables Host
Aware partitioning for the cluster.
|====

See here for an example configuration demonstrating each property:

----
<config name="server-config">
    ...
    <hazelcast-runtime-configuration enabled="true" hazelcast-configuration-file="hazelcast-configuration.xml" start-port="5666" multicast-group"224.2.2.4" jndi-name="payara/Hazelcast1 multicast-port="54328" host-aware-partitioning="true"></hazelcast-runtime-configuration>
    ...
</config>
----

== Setting Hazelcast as the Persistence Provider

_Note that you can always select Hazelcast as a persistence provider, even if
it it not yet enabled._

=== Setting Web Persistence

To set Hazelcast as the persistence provider of the web container, edit the
_domain.xml_ as follows:

----
<config name="<cluster-config>">
    ...
    <availability-service>
        ...
        <web-container-availability persistence-type="hazelcast"></web-container-availability>
        ...
    </availability-service>
    ...
</config>
----

=== Setting EJB Persistence

To set Hazelcast as the persistence provider of the web container, edit the
_domain.xml_ as follows:

----
<config name="${Cluster-Config}">
    ...
    <availability-service>
        ...
        <ejb-container-availability sfsb-ha-persistence-type="hazelcast"></ejb-container-availability>
        ...
    </availability-service>
    ...
</config>
----
